- name: reload systemd or daemon_reload
  ansible.builtin.systemd_service:
   daemon_reload: true   

- name: start service
  ansible.builtin.service:
    name: user
    state: restarted
    enabled: yes   
